from __future__ import annotations

import pyarrow as pa

EDGE_SCHEMA = pa.schema([
    ("decision_time", pa.timestamp("ns", tz="UTC")),
    ("window_start", pa.timestamp("ns", tz="UTC")),
    ("window_end", pa.timestamp("ns", tz="UTC")),
    ("layer_id", pa.int16()),
    ("lookback_minutes", pa.int16()),
    ("scale_role", pa.string()),
    ("decision_step_minutes", pa.int16()),
    ("top_k", pa.int16()),
    ("degree_cap", pa.int16()),
    ("minimum_similarity", pa.float32()),
    ("src_id", pa.int32()),
    ("dst_id", pa.int32()),
    ("weight", pa.float32()),
    ("src_rank", pa.int16()),
    ("dst_rank", pa.int16()),
    ("directed", pa.bool_()),
    ("lag_bars", pa.int16()),
    ("window_points", pa.int16()),
    ("vector_dimension", pa.int16()),
])
NODE_SCHEMA = pa.schema([
    ("decision_time", pa.timestamp("ns", tz="UTC")),
    ("layer_id", pa.int16()),
    ("lookback_minutes", pa.int16()),
    ("scale_role", pa.string()),
    ("decision_step_minutes", pa.int16()),
    ("top_k", pa.int16()),
    ("degree_cap", pa.int16()),
    ("minimum_similarity", pa.float32()),
    ("symbol_id", pa.int32()),
    ("degree", pa.int16()),
    ("strength", pa.float32()),
    ("core_z", pa.float32()),
    ("neighbor_reversal", pa.float32()),
    ("neighbor_signed_flow", pa.float32()),
    ("layer_participation", pa.float32()),
])
SNAPSHOT_SCHEMA = pa.schema([
    ("decision_time", pa.timestamp("ns", tz="UTC")),
    ("window_start", pa.timestamp("ns", tz="UTC")),
    ("window_end", pa.timestamp("ns", tz="UTC")),
    ("layer_id", pa.int16()),
    ("lookback_minutes", pa.int16()),
    ("scale_role", pa.string()),
    ("decision_step_minutes", pa.int16()),
    ("top_k", pa.int16()),
    ("degree_cap", pa.int16()),
    ("minimum_similarity", pa.float32()),
    ("universe_count", pa.int32()),
    ("active_nodes", pa.int32()),
    ("node_coverage", pa.float32()),
    ("isolated_node_ratio", pa.float32()),
    ("edge_count", pa.int32()),
    ("degree_cap_saturation", pa.float32()),
    ("mean_degree", pa.float32()),
    ("mean_strength", pa.float32()),
    ("window_points", pa.int16()),
    ("vector_dimension", pa.int16()),
    ("lsh_bits", pa.int16()),
    ("used_columns", pa.string()),
    ("transform", pa.string()),
    ("weight_p50", pa.float32()),
    ("weight_p75", pa.float32()),
    ("weight_p90", pa.float32()),
    ("weight_p95", pa.float32()),
    ("weight_p99", pa.float32()),
    ("top_1pct_mean_weight", pa.float32()),
    ("tail_mass_95", pa.float32()),
    ("elapsed_ms_total_snapshot", pa.int32()),
])
